### ISSUE TITLE
Hey trying to reach you and you are unresponsive on twitter

### ISSUE THREAD

**Issue by nhatzfeld** [roninjin10/stax#9]
I saw you had made commits to the OP repo. We are launching an OP l2 fork and looking for devs to help us. This would a full time employment working with a super cool team. I'd love to make some intros if you are interested.

You can reach me on twitter https://twitter.com/moderndiogenese

Or on telegram @NathanSyscoin

Or email if you prefer Nathan@Syscoin.org

Our website is Syscoin.org

We have a really cool data solution that is done and hooked into Bedrock. Lots of cool happenings in our company and ecosystem and would love to speak more formally. Thank you.

**Comment by roninjin10** [comment]
Hey @nhatzfeld that's amazing!   I actually work at OP labs and I am really excited to hear you are building on top of bedrock!   I will let folks at OP labs know and someone might reach out to you
